theme: jekyll-theme-minimal
title: Dmitry Surchin
description: >- # this means to ignore newlines until "baseurl:"
 Student (Information Science) at Higher Vocational College B2</br>
 Live in Ljubljana, Slovenia
logo: https://life-termer.github.io/assets/logo.png
show_downloads: true
baseurl: https://life-termer.github.io
plugins:
  - jekyll-feed
